source 'http://rubygems.org/'

gemspec

group :development, :test do
  gem "rake"
  gem "rspec"
  gem "guard", "~> 1.3.2"
  gem "guard-rspec", "~> 2.1.1"
  gem "rb-fsevent", "~> 0.9.1"
end

group :test do
  gem "factory_girl"
end